### PR TITLE
[WIP]feat: refactor CRD datasource to fit product design

### PR DESCRIPTION
**Pull request by bjwswang**
#### What type of PR is this?
/kind refactor

#### Which issue(s) this PR fixes

Fixes #

### CODE REVIEW

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /review

**Comment by bjwswang** [comment]
@CodiumAI-Agent /review

**Comment by bjwswang** [comment]
@CodiumAI-Agent /review

**Comment by bjwswang** [comment]
@CodiumAI-Agent /improve

**Comment by bjwswang** [comment]
@CodiumAI-Agent  /update_changelog

**Comment by bjwswang** [comment]
@CodiumAI-Agent /update_changelog --pr_update_changelog.push_changelog_changes=true

**Comment by bjwswang** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
