### PR TITLE
chore:able to publish our data-processing server to pypi

### LINKED ISSUE #612: able to publish our data-processing server to pypi

### LINKED ISSUE #698: upgrade dataprocessing python version to 3.11.5
Before release the v0.2.0 ,we need to use same python version in our python projects 

- data-processign
- ragas_once

@ggservice007 @wangxinbiao

### PR DESCRIPTION
**Pull request by wangxinbiao**
#### What this PR does / why we need it

chore:able to publish our data-processing server to pypi
#### Which issue(s) this PR fixes

Fixes #612 
Fixes #698

### CODE REVIEW

**Comment by nkwangleiGIT** [comment]
something we should cover:
1. rename one_data_processing to something like kubeagi.dp, so developers can easily import the package and use it in their python code, for example:
```
from kubeagi.dp import PdfHandler
```
2. add some samples about how to use kubeagi.dp, take mlflow, unstructured as example
3. move data-processing and ragas out of arcadia as a separate project, focus on SDK and tool to support kubeagi platform.

**Comment by bjwswang** [comment]
> something we should cover:
> 
> 1. rename one_data_processing to something like kubeagi.dp, so developers can easily import the package and use it in their python code, for example:
> 
> ```
> from kubeagi.dp import PdfHandler
> ```
> 
> 2. add some samples about how to use kubeagi.dp, take mlflow, unstructured as example
> 3. move data-processing and ragas out of arcadia as a separate project, focus on SDK and tool to support kubeagi platform.

Agree! We should move the projects under `pypi` out of this arcadia project. Since we have data-processing and ragas_once(a evaluation CLI) We should consider to give it a more common name.

**Comment by nkwangleiGIT** [comment]
Let's use core-library as code repo to contain python sdks, we can introduce APIs or client later to easily use core libraries.

**Comment by bjwswang** [comment]
done @nkwangleiGIT @wangxinbiao  https://github.com/kubeagi/core-library

**Pull request closed without merging**
