### PR TITLE
fix:find the permissions needed for the command gen_test_dataset

### PR DESCRIPTION
**Pull request by xxxxibo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it
Find the permissions needed for the command gen_test_dataset

#### Which issue(s) this PR fixes

Fixes #

### CODE REVIEW

**Comment by bjwswang** [comment]
@0xff-dev  Is this good enough?  Should we add the cluster role permissions ? 

```shell
1.7067048284279842e+09  ERROR   Reconciler error        {"controller": "namespace", "controllerGroup": "", "controllerKind": "Namespace", "namespace": {"name":"kube-system"}, "namespace": "", "name": "kube-system", "reconcileID": "97dd6165-232f-492d-8b3a-76e8ace5441f", "error": "Operation cannot be fulfilled on clusterrolebindings.rbac.authorization.k8s.io \"ragas-eval-clusterrolebinding\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
```

**Comment by 0xff-dev** [comment]
> @0xff-dev Is this good enough? Should we add the cluster role permissions ?
> 
> ```shell
> 1.7067048284279842e+09  ERROR   Reconciler error        {"controller": "namespace", "controllerGroup": "", "controllerKind": "Namespace", "namespace": {"name":"kube-system"}, "namespace": "", "name": "kube-system", "reconcileID": "97dd6165-232f-492d-8b3a-76e8ace5441f", "error": "Operation cannot be fulfilled on clusterrolebindings.rbac.authorization.k8s.io \"ragas-eval-clusterrolebinding\": the object has been modified; please apply your changes to the latest version and try again"}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
>         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
>         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
> ```

The error reported here is from the controller, while trying to bind `serviceaccount` to `clusterrolebinding`, the resource changed and needs to be updated again.
It has nothing to do with the permissions of this PR.

The controller's permissions to operate on clusterrolebiding have been updated in `rbac.yaml` in the helm package

**Comment by nkwangleiGIT** [comment]
I also noticed that the controller report the warning some frequent:
```
please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
```
@0xff-dev  pls check why it's always conflict while binding serviceaccount to clusterrolebinding, can we try to avoid this?

**Comment by bjwswang** [comment]
Seems we are trying to modify the same `clusterrolebinding` in parallel.We have two options:

option 1: maintain a clusterrolebinding for each ns 
option 2: make sure the namespace controller process events sequencially

**Comment by bjwswang** [comment]
@xxxxibo Please rebase your branch

**Review by bjwswang — APPROVED** [review]

**Pull request merged**
