### PR TITLE
feat: develop knowledgebase API

### LINKED ISSUE #206: Develop knowledgebase API
- [x] create knowledgebase 
- [x] update knowledgebase ( only supports editint of "displayname")
- [x] get knowledgebase
- [x] delete knowledgebase

### PR DESCRIPTION
**Pull request by zqq454224016**
#### Which issue(s) this PR fixes

Fixes #206

### CODE REVIEW

**Comment by bjwswang** [comment]
@Abirdcfly pls work with @zqq454224016  on Knowledge APIs

**Review by bjwswang — APPROVED** [review]

**Comment by nkwangleiGIT** [comment]
@0xff-dev can the auto-generated go files and manually written files be separated by different folder?

**Comment by 0xff-dev** [comment]
> @0xff-dev can the auto-generated go files and manually written files be separated by different folder?

https://github.com/kubeagi/arcadia/pull/219
- *.graphqls in `schema`
- resolvers in `impl`

`generated` and `model` It's all automatically generated.

**Review by bjwswang — CHANGES_REQUESTED** [review]
sync with latest graphql structure

**Pull request closed without merging**
